### PR TITLE
extract func output below current func

### PR DESCRIPTION
**Pull request by rdallman**
this just kind of bugged me, I believe someone else expressed a similar
sentiment that the extracted func should be output below the current enclosed
func rather than at the bottom of the file. this does that. also added an
extra newline preceding the extracted function. this tends to be programmer
preference for whether to put associated functions above or below their caller
(or, for that matter, anywhere remotely close) -- it's rather pedantic to
bicker over, I could put it above if someone so prefers that to be the
default; we could also easily make it configurable.

updated the tests by hand to make sure I didn't fuck anything up. should check
out

p.s. I had a go at fixing the issues with anonymous function extraction. seems the error bubbles up from the ast package, may look further into this soon as it's a pretty big 'gotcha' and seems like our analyses our robust enough to cover it currently.

### CODE REVIEW

**Comment by rdallman** [comment]
@joverbey could you review please?

**Comment by rdallman** [comment]
closes https://github.com/godoctor/godoctor/issues/21

**Comment by joverbey** [comment]
Awesome.  Thanks for doing this!  It was at the top of my list.  Will try it out ASAP, probably Saturday (swapping some stuff around on my machines...)

**Comment by rdallman** [comment]
holiday bump @joverbey 

... joverbump? :D

HH

**Comment by joverbey** [comment]
Ack, so sorry... I totally lost track of this, and Gmail is sending all my GitHub mail to junk again.  Looking at it now.

**Comment by joverbey** [comment]
LGTM.  It introduces a syntax error (and detects it) in this pathological case...
```go
package main
import "fmt"
func main() {
»       fmt.Printf("Hi\n") // Extract me
}; func meh() { }
```
...but I can't imagine anyone doing that in production code, so I don't think it's worth worrying about.

I've been wanting this feature for a long time.  Thanks so much.

What's the ETA on Go 1.8?  If it's soon, how about if I add a pointer to the emacs plug-in to the documentation, then we can vendor for 1.8, and package this up with all of that and call it version 0.4?

**Comment by rdallman** [comment]
thanks!

>  It introduces a syntax error (and detects it) in this pathological case

good catch. it's a tricky code rewrite, as well. where should the extracted func be placed? after `meh()`? In other words, before the next package level func that is declared on its own line (or EOF)? I think this should be do-able with a little digging around in the file, I'll try to look into it soon enough.

> What's the ETA on Go 1.8?

feb. package away.

**Pull request merged**
