### PR TITLE
V0.6 prerelease

### LINKED ISSUE #42: Function Extract failure
Hi
Hopefully this isn't user error, but I've found a pattern I use in some of my code that seems to really upset the extract feature.  In my tiddly test case I see an even weirder error where any attempt to extract anything says: "Error: invalid selection: An empty block cannot be extracted"
But  when this pattern exists in my larger codebases the Extract function succeeds, but creates invalid variables that clash with the existing namespace.
Anyway, here's the noddy code:
`package main

import (
  "fmt"
  "strings"
)

func main() {
  inputString := "bob"
  listOfWork := []string{"a", "b", "c"}
  var workDone bool

  // This for loop can't seem to be extracted with any success
  for _, wrk := range listOfWork {
    if strings.Contains(inputString, wrk) {
      workDone = true
      inputString = strings.Replace(inputString, wrk, ".", -1)
    }
  }

  if workDone {
    fmt.Println("done something")
  }
}
`

### LINKED ISSUE #43: Extract Function failure - variable's previous value ignored
From issue #42 ...

I'm not sure if you would rather this were raised as a separate issue, but during my experimentation I discovered a situation where the extract function can produce incorrect code.
If you do a similar pattern where in the code you extract you modify a bool, then unless in that code you explicitly read the bool first then the current value of the bool is ignored. 
```
package main

import (
	"fmt"
	"strings"
)

func main() {
	inputString := "bob"
	missingSuffix := true
	// If you extract this if
	// then it ignores the current value of missingSuffix
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}

	fmt.Print("string:", inputString)
	if missingSuffix {
		fmt.Println(" is missing Suffix")
	} else {
		fmt.Println(" contains Suffix")
	}
}
```
Extracting the commented on if, gives you:
```
	missingSuffix = fred(inputString)


func fred(inputString string) bool {
	var missingSuffix bool
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}
	return missingSuffix
}
```
Which will give you the incorrect result.

### PR DESCRIPTION
**Pull request by joverbey**
@rdallman @roberthorn @cbehopkins if you get a few minutes, could you try out this branch (v0.6-prerelease) in the next week or two?  I'd really like your feedback on one issue in particular.

My main concern is my fix for #43.  Now, the Extract Function refactoring is a bit more aggressive about declaring local variables rather than passing parameters.  For example, consider this:

```go
	inputString := "bob"
	missingSuffix := true
	if strings.Contains(inputString, "Suffix") { // <<<<< Extract this if-statement
		missingSuffix = false
	}
	fmt.Println(inputString, missingSuffix)
```

Before, we would have passed `inputString` and `missingSuffix` as arguments (well, except for the bug mentioned in #43).  With this change, since they are assigned constant values, we redeclare them as locals in the extracted function, assigning them the correct values.

```go
func check() bool {
	inputString := "bob"
	missingSuffix := true
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}
	return missingSuffix
}
```

I think this is generally closer to what I would have done by hand, but I'd like your opinions.  It's easy to revert (or change) if we decide we don't like it.

- Fixes #42 
- Fixes #43 
- Updated version to 0.6
- Improved the debug refactoring - added options to show data flow information
- Updated vendored dependencies
- Tested with Go 1.8, 1.9, and 1.10

### CODE REVIEW

**Comment by cbehopkins** [comment]
Testing results:
I've tested the fix for 43 and success - Many thanks!

I'm not convinced by the fix for 44 as the variable initialisation I showed there was part of the test case, not a realistic example of the pattern. I understand why it is easier to change the selection part of the extract function to catch this, but I'm not sure in most cases this would be the right thing to do. The actual cases I saw this behaviour was in situations where an item is tested against a condition multiple times. Or perhaps more generically you have a common input which has several operation run on it, and they produce some form of boolean result as part of that operation.
An example is worth a thousand lines of waffling!:
Say instead I had:
```
func main() {
	inputString := "bob"
	missingSuffix := true
	if strings.Contains(inputString, "Extension") {
		missingSuffix = false
	}	
        // Extract this if statement
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}


	fmt.Print("string:", inputString)
	if missingSuffix {
		fmt.Println(" is missing Suffix")
	} else {
		fmt.Println(" contains Suffix")
	}
}
```
Then this produces:
```
func main() {
	inputString := "bob"
	missingSuffix := true
	if strings.Contains(inputString, "Extension") {
		missingSuffix = false
	}

	missingSuffix = fred(missingSuffix)

	fmt.Print("string:", inputString)
	if missingSuffix {
		fmt.Println(" is missing Suffix")
	} else {
		fmt.Println(" contains Suffix")
	}
}

func fred(missingSuffix bool) bool {
	inputString := "bob"
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}
	return missingSuffix
}
```
Which is tantalisingly close to my ideal code, which would be:
```
func main() {
	inputString := "bob"
	missingSuffix := true
	if strings.Contains(inputString, "Extension") {
		missingSuffix = false
	}

	missingSuffix = fred(missingSuffix, inputString)

	fmt.Print("string:", inputString)
	if missingSuffix {
		fmt.Println(" is missing Suffix")
	} else {
		fmt.Println(" contains Suffix")
	}
}

func fred(missingSuffix bool, inputString string) bool {
	if strings.Contains(inputString, "Suffix") {
		missingSuffix = false
	}
	return missingSuffix
}
```
I appreciate this is quite a tricky situation, but it looks like it's so very close to perfect.

**Comment by cbehopkins** [comment]
Playing around, a testcase that shows incorrect functionality code generated:
```
func main() {
	inputString := "bob"
	missingSuffix := true
	if strings.Contains(inputString, "Extension") {
		missingSuffix = false
	} 
	for _, tf := range []string{"Suffix", "steve"} {
		// If you extract this if
		// Then it does the wrong function
		if strings.Contains(inputString, tf) {
			missingSuffix = false
		}
	}

	fmt.Print("string:", inputString)
	if missingSuffix {
		fmt.Println(" is missing Suffix")
	} else {
		fmt.Println(" contains Suffix")
	}
}
```

**Comment by cbehopkins** [comment]
FWIW I've tested this against the actual refactoring I was doing when I started this (github.com/cbehopkins/medorg/autofix.go) and it worked great - including the boolean parts that weren't working are now fixed - they did not pull in the constant declaration to their local scope (There were none nearby to pull in).
So IMO (except for above testcases), this seems to be fixed.
Many many thanks for your help

**Comment by joverbey** [comment]
Great, thanks for trying this out!

FWIW, my thinking was this.  Except in test cases, an input (like your `inputString`) will be read from a file, or it will be the result of a function call, or something nontrivial like that.  So if a function is extracted, that variable containing that input will be passed as an argument -- which is exactly what you want.  I think it's actually pretty rare to see `variable := 0` or `variable := "literal"` in production code, except as initialization code just above a loop (or something) that updates that variable to its final value.  I have a big database of Go code... let me look around it a bit and see how often that pattern really occurs.

It will be really easy to change this behavior, passing all variables as arguments instead, if we decide to.  Actually, that's easier.  :)

**Pull request merged**
