### PR TITLE
Extract local

### PR DESCRIPTION
**Pull request by joverbey**
I spent the weekend cleaning up @wfrazier002 's Extract Local Variable refactoring, adding some more tests and preconditions and running it through 100 Go Patient test cases.

@rdallman @roberthorn if you get a chance, please try it out and let me know how it goes.

The list of preconditions <https://github.com/godoctor/godoctor/blob/extract-local/refactoring/extractlocal.go#L61> is absurdly long.  The AST uses various ast.Expr nodes (notably, identifiers) for all sorts of things -- including type names -- so there's a ton of logic to try to figure out if the expression occurs in a context where it can legitimately be extracted.

There are several cases where we _could_ extract a variable but currently don't allow it.  Notably, you can't extract expressions from for loop headers, switch statement headers, decl statements, go, defer, select, send, and switch statements.  So, I'm mainly curious to see if I need to whitelist more of those cases.  (Not hard, but it means more preconditions and more test cases.)

Extracting from for-loop headers seems like something I should allow, but it's tricky since you have to make sure the extracted expression is loop invariant, which means using Reed's reaching definitions analysis.  Maybe later...

### CODE REVIEW

**Comment by rdallman** [comment]
LGTM, no other cases that I could think of in my admittedly brief time spent trying to think up other cases where there would be breakage, seems to catch name conflicts already too. there are a lot of tests :) thanks. 

I'll add that I did find it a little confusing on a few of the exceptions, of which you noted here:

> Notably, you can't extract expressions from for loop headers, switch statement headers, decl statements, go, defer, select, send, and switch statements. So, I'm mainly curious to see if I need to whitelist more of those cases. 

2 cases I can think of that I don't see tests for and can't discern whether they are excepted from notes or code are:

for example:

```go
x := map[string]string{
  "b"+"oo": "foo", // extract local "b"+"oo" -> newVar
}

->

// is this a key value expr and will fail? expect:
newVar := "b"+"oo"
x := map[string]string{
  newVar: "foo"
}
```

The key production is either a Fieldname, an expression or a literal, it seems like we should limit the scope of blocking this only to Fieldname and allow literals or expressions (the latter I'm much less sure of, it seems a slippery slope..)

the other, which I simply see no test case for and it was alluded to not to allow from decl statements, so I'll share:

```go
x := []{1+2, 4, 5} // extract local 1+2 -> newVar

-> 

// inside of decl succeeds?
newVar := 1+2
x = []{newVar, 4, 5}
```

+1 on reaching defs for for loop condition extraction, that'd be pretty cool. it took me a minute to figure out what the problem was, but I get it now, if it's e.g. `for a+b < 3 { a++ }` make sure e.g. `a` and `b` are not mutated inside the loop body before allowing extraction, so that we could not allow extraction. pretty cool! not sure how hard to hook up, however.

Perhaps the above cases already work (I could probably go try myself, yes, fuck me)? I cannot think of anything else. I think this is absolutely okay to release as is, looks great, thanks.

**Comment by rdallman** [comment]
merge away*

**Comment by rdallman** [comment]
It would also be really cool if we could find aliases of expressions but I don't think it's at all necessary, if even easily possible, e.g.

```go
if a+b > 3 { // extract a+b
  fmt.Println(a+b)
}

-> 

newVar := 3
if newVar > 3 {
  fmt.Println(newVar)
}
```

We would have to traverse every statement in scope and check if it's equivalent and unmodified up to that point (and ?) so it wouldn't be cheap in some cases. I end up doing that kind of thing often. Anyway, don't mean to add stuff, sure you came across this as well, just +1'ing I guess (and inquiring about ease...)

**Comment by joverbey** [comment]
Thanks a lot for looking at it!  The other cases you mentioned are good ones; I'll check on those and add some tests.  I didn't even realize you could use an expression as a key.

I might try to add some of the excluded cases (esp. for loops), because I'm running into them and it's annoying.  Depends on free time.

Extracting clones would be very cool.  Might tackle that next.  It's tricky for all the reasons you mentioned.  Even finding the correct insertion point is nontrivial, e.g.,
```go
	x, y, z := 1, 2, 3
        // extracted := y + z would have to be inserted here
	for i := 0; i < 2; i++ {
		if y < z {
			x = y + z // Extract y + z
		}
	}
	if true {
		x = y + z // Extract y + z
	}
	fmt.Println(x, y, z)
```
You can build a dominator tree from the control flow graph and use that (dominators model the notion of "if you reach this statement in the function, then these other statements have definitely executed along the way"), but if you exclude goto statements, I think it boils down to finding the smallest BlockStmt that contains all of the clones.  Thinking about this...

(Off-topic, I'm also thinking about how to improve renaming in comments, which has caused some unwelcome accidents for me... I think I renamed a local variable named "a" and then it destroyed comments throughout the file or something...)

**Comment by joverbey** [comment]
Hey @rdallman and @roberthorn 

I finally added the ability to extract from if-statement and for-loop headers.  Nice use of the reaching definitions analysis.

If you could give it a spin, let me know how it works.  Then I can merge it in and call this version 0.5.  Hopefully we can have 1.0 soon.  :)

Re: issues mentioned above...

1. What you mentioned about map keys...
```go
boo := "b" + "oo"
x := map[string]string{
    boo: "foo",
}

type S struct {
    boo string
}
y := S{
    boo: "foo", //<<<<< var,15,3,15,5,newVar2,fail
}
```
In the first case, `boo` is an expression (which should be extractable); in the second case, it's a field name (which should not).  You can't tell the difference between the two using only the AST, so I would need to ask go/types to figure this out.  This is still on the to-do list.

2. Recarding `DeclStmt`s: I added two tests.  This current behavior is not intuitive:
```
x := []int{1 + 2, 4, 5} //<<<<< var,6,13,6,17,newVar,pass
var x []int = []int{1 + 2, 4, 5} //<<<<< var,6,22,6,26,newVar,fail
```
`DeclStmt`s are slightly tricky because (1) `const`, `type`, and `var` statements are all `DeclStmt`s, and (2) `DeclStmt`s can occur at the top level, not necessarily inside a function.  Nevertheless, it wouldn't be hard to fix.  This is also on my to-do list.

Clone detection would also be useful, as we discussed.

**Comment by rdallman** [comment]
> I finally added the ability to extract from if-statement and for-loop headers. Nice use of the reaching definitions analysis.
>
> If you could give it a spin, let me know how it works. Then I can merge it in and call this version 0.5. Hopefully we can have 1.0 soon. :)

sweet. yea, works for me. really cool.

> In the first case, boo is an expression (which should be extractable); in the second case, it's a field name (which should not). You can't tell the difference between the two using only the AST, so I would need to ask go/types to figure this out. This is still on the to-do list.

makes sense. 

LGTM, :shipit:

**Pull request merged**
